use super::Tutorial;

pub fn export_markdown(tutorial: &Tutorial) -> String {
    let mut markdown = String::new();

    // Title
    markdown.push_str(&format!("# {}\n\n", tutorial.title));

    // Description
    markdown.push_str(&format!("{}\n\n", tutorial.description));

    // Metadata
    markdown.push_str("## Overview\n\n");
    markdown.push_str(&format!("- **Estimated Duration:** {} minutes\n", tutorial.estimated_duration));
    markdown.push_str(&format!("- **Difficulty:** {}\n", tutorial.difficulty));

    if !tutorial.tags.is_empty() {
        markdown.push_str(&format!("- **Tags:** {}\n", tutorial.tags.join(", ")));
    }

    markdown.push_str("\n---\n\n");

    // Steps
    markdown.push_str("## Steps\n\n");

    for step in &tutorial.steps {
        markdown.push_str(&format!("### {} - {}\n\n", step.step_number, step.title));
        markdown.push_str(&format!("{}\n\n", step.description));

        if let Some(ref code) = step.code_snippet {
            markdown.push_str("```bash\n");
            markdown.push_str(code);
            markdown.push_str("\n```\n\n");
        }

        if let Some(ref screenshot) = step.screenshot_path {
            markdown.push_str(&format!("![Screenshot]({})\n\n", screenshot));
        }

        if !step.tips.is_empty() {
            markdown.push_str("**Tips:**\n\n");
            for tip in &step.tips {
                markdown.push_str(&format!("- {}\n", tip));
            }
            markdown.push_str("\n");
        }

        markdown.push_str("---\n\n");
    }

    // Footer
    markdown.push_str("## Summary\n\n");
    markdown.push_str(&format!("Congratulations! You've completed the \"{}\" tutorial.\n", tutorial.title));
    markdown.push_str("\n");
    markdown.push_str("*Generated by ShadowLearn - Learn by Doing*\n");

    markdown
}
